# Generated by Django 5.2.15 on 2026-07-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_availability_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
