# Generated by Django 5.2.15 on 2026-07-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_session_unique_together_session_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending_tutor', 'Pending Tutor'), ('pending_learner', 'Pending Learner'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
