# Generated by Django 5.2.15 on 2026-07-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_slots',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
