# Generated by Django 5.2.15 on 2026-07-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_add_post_time_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
