# Generated by Django 5.2.16 on 2026-07-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_photo_as_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='meeting_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
