# Generated by Django 5.2.16 on 2026-08-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_session_meeting_link_session_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='learner_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='session',
            name='tutor_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
