# Generated by Django 5.2.16 on 2026-08-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_session_learner_notes_session_tutor_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
